### ISSUE TITLE
Reset button is not working on failure in Add graph rule and Add package. 

### ISSUE THREAD

**Issue by spathare21** [transtats/transtats#108]
##### ISSUE TYPE

 - Bug Report

##### OS / ENVIRONMENT

```
Fedora 26 + Chrome & Firefox 
```

##### SUMMARY
- If there is a failure while adding packages/graph rule reset buttons is not clearing all set values to null/blank
##### STEPS TO REPRODUCE
- Go to packages tab
- Click on Add package 
- Fill the all invalid details so it should failed to add package
- Try to reset the values after failure

```

```

##### EXPECTED RESULTS
- Reset button sould work even after failure 

##### ACTUAL RESULTS
- Reset button is not working in failure of adding package/graph rule

![screenshot from 2018-02-26 16-19-55](https://user-images.githubusercontent.com/23230884/36671019-37281cbe-1b20-11e8-8d2f-e38698aa35a7.png)
![screenshot from 2018-02-26 16-21-23](https://user-images.githubusercontent.com/23230884/36671020-375453f6-1b20-11e8-8773-d0422ec6d5e7.png)

**Comment by sundeep-co-in** [comment]
solved with https://github.com/transtats/transtats/pull/167
