### ISSUE TITLE
Jobs running in parallel fail to complete.

### ISSUE THREAD

**Issue by spathare21** [transtats/transtats#114]
##### ISSUE TYPE
 - Feature Idea

##### SUMMARY

- Currently, if we run multiple jobs at the same time some jobs half log are missing
As discussed with Sundeep it will be archived by multithreading.

**Comment by sundeep-co-in** [comment]
thanks @spathare21 for raising this!

**Comment by spathare21** [comment]
Hi,  found the following issues with string job templates 

1. Job status shows failed in inspect logs when it's running
2. If we start a job and switch to different tab job looks aborted/failed   
3. If we run two or more string change jobs parallelly git cloning fails for one job or both

**Comment by spathare21** [comment]
1 st ran job fails for cloing master branch if we ran 2 or more Sync package upstream job parallel

**Comment by spathare21** [comment]
Getting 504 gateway timeout intermittently for jobs

**Comment by juhp** [comment]
How about just avoiding to run conflicting jobs in parallel?

**Comment by juhp** [comment]
Can we rename this issue to describe the problem not the solution?

**Comment by juhp** [comment]
Does it only affect logging?

**Comment by sundeep-co-in** [comment]
Actually, there is one location - jobs share to run. Hence the issue. Here we have two tasks:
- [ ] Exclusive location and logging process to each job.
- [ ] Complete logging of jobs even if it fails. *(currently logging is incomplete if job fails)*

**Comment by sdp5** [comment]
this has been achieved for Pipeline Config jobs in https://github.com/transtats/transtats/commit/ec3acd012e20f202bcbf8fd83c858a40bb1d3ae1
