### ISSUE TITLE
bootstrap transtats

### ISSUE THREAD

**Issue by sdp5** [transtats/transtats#118]
`transtats` has some components which should be enabled environment / targeted-instance wise.

Lets spend sometime looking `how to bootstrap transtats for different tenants`

**Comment by sundeep-co-in** [comment]
:link: about-us

**Comment by sdp5** [comment]
Multi-tenancy has been achieved in https://github.com/transtats/transtats/commit/93451918239d87d4e15267cb780c97d52440faea
