### ISSUE TITLE
package validation needed for syncdownstream job type

### ISSUE THREAD

**Issue by pnemade** [transtats/transtats#140]
##### ISSUE TYPE

 - Bug Report

##### SUMMARY
syncdownstream job type should also do package validation first.

##### STEPS TO REPRODUCE
./transtats job run syncdownstream brt --build_system koji --build_tag f29 --json

##### EXPECTED RESULTS
should give package does not exists

##### ACTUAL RESULTS
proceeds executing job

**Comment by sundeep-co-in** [comment]
would addition of new API endpoint `GET /api/package/<package-name>/exist` seem meaningful here?
- introducing it with [this](https://github.com/transtats/transtats/pull/138/commits/9a8667196d3325879395235e2452d3d1b63e6a4d) commit.

**Comment by spathare21** [comment]
yup validation is working now error message : Upstream URL could NOT be located for qwerqwe package

**Comment by sundeep-co-in** [comment]
@pnemade are we good closing this?

**Comment by pnemade** [comment]
Nothing left here to fix.
