### ISSUE TITLE
Validation required for release_slug parameter for stringchange job

### ISSUE THREAD

**Issue by pnemade** [transtats/transtats#141]
##### ISSUE TYPE
 - Bug Report

##### SUMMARY
stringchange job should validate release_slug option value.

##### STEPS TO REPRODUCE
./transtats job run stringchange iok --release_slug f30 

##### EXPECTED RESULTS
job should not be submitted for invalid release_slug

##### ACTUAL RESULTS
job get submitted with invalid release_slug

**Comment by sundeep-co-in** [comment]
hope this would be fixed with [this](https://github.com/transtats/transtats/pull/138/commits/9a8667196d3325879395235e2452d3d1b63e6a4d) commit.

**Comment by spathare21** [comment]
validation for release is working now with latest code error message : No branch mapping for abrt package of test release.

**Comment by sundeep-co-in** [comment]
@pnemade is anything left here?

**Comment by pnemade** [comment]
Nothing left here to fix.
