### ISSUE TITLE
String change job logs and error message

### ISSUE THREAD

**Issue by spathare21** [transtats/transtats#142]
##### ISSUE TYPE

 - Bug Report

##### OS / ENVIRONMENT
```
Fedora 28 
```

##### SUMMARY
- Logs shown for ran job are not in sequence 

##### STEPS TO REPRODUCE
- Open transfats instance 
- Go to the jobs section 
- Run string change job for any package and release 
- Observe the logs 

##### EXPECTED RESULTS
- Logs shown should be in sequence 

##### ACTUAL RESULTS
- Logs are no showing in sequence like first it shows line no 937 then 1763 and then 1223

![screenshot from 2018-08-01 18-49-03](https://user-images.githubusercontent.com/23230884/43626897-8564b97e-9711-11e8-86ee-7888373c6a20.png)

**Comment by spathare21** [comment]
Error messages on string change job should be generic

**Comment by sundeep-co-in** [comment]
can be achieved with #168 and #23
