### ISSUE TITLE
Please disambiguate Portuguese language

### ISSUE THREAD

**Issue by rluzynski** [transtats/transtats#145]
##### ISSUE TYPE

 - Bug Report

##### OS / ENVIRONMENT

All (website)

##### SUMMARY

Please split Portuguese into Portuguese (as spoken in Portugal) and Portuguese (Brazil).
##### STEPS TO REPRODUCE

Currently the list of languages in Transtats contains Portuguese and says that its locale code is ```pt_BR```. While it may seem to be correct at first sight in fact it is not. The locale code for Portuguese should be ```pt_PT```, and ```pt_BR``` is for Portuguese (Brazil). This is how Zanata names these languages, other sources may provide different disambiguation (e.g., Brazilian Portuguese).

The differences between these languages are minor (similar to UK English and US English) but the locale codes and translation teams are different.

##### EXPECTED RESULTS

* Have two variants of Portuguese, my suggestion is: ```Portuguese``` and ```Portuguese (Brazil)```.
* Assign them the correct locale codes: ```pt_PT``` and ```pt_BR```, respectively.

##### ACTUAL RESULTS

* Only one variant of Portuguese is supported.
* Additionally, its locale code is incorrect. (Or: if the locale code is correct then the name is incorrect.)

**Comment by sundeep-co-in** [comment]
thanks @rluzynski submitting this!

**Comment by rluzynski** [comment]
Thank you, @sundeep-co-in. Your fix closes this issue, however it seems that the "fixes" keyword does not close the issue automatically. I'm closing manually.
