### ISSUE TITLE
name mapping

### ISSUE THREAD

**Issue by sdp5** [transtats/transtats#148]
##### ISSUE TYPE

 - Feature Idea

##### SUMMARY
Some of the packages have different package name in build system from that of in source repo. So, some name mapping should be there to handle such scenario.

for example: `welder-web` is packaged as `cockpit-compose`

**Comment by sundeep-co-in** [comment]
one more example: `network-manager-applet` is translated at zanata as project: `nm-applet`

**Comment by sundeep-anand** [comment]
few more `python-blivet` and `policycoreutils`

**Comment by sdp5** [comment]
this has been achieved in https://github.com/transtats/transtats/pull/246/commits/efeb5425c5217c6e044daea7a9586458648fc9c4
