### ISSUE TITLE
Release Branch Mapping

### ISSUE THREAD

**Issue by sundeep-co-in** [transtats/transtats#15]
Currently, graph rules can only be created for master branch. To expand the support for other branches, some mapping is required for each package. Mapping between: upstream releases - translation platform versions - release branches!

- [x] associating language-set with release branch makes more sense than with packages
- [x] provision branch mapping rule for every package
- [x] implement language-set and branch mapping in custom graphs

**Comment by sshedmake** [comment]
graph for 'ovirt-engine-jrs-branding' has no 'release' specific branch (needs mapping)
