### ISSUE TITLE
Spelling of "Norwegian Bokmål"

### ISSUE THREAD

**Issue by rluzynski** [transtats/transtats#150]
##### SUMMARY

It's a really minor and trivial problem but I've checked in multiple sources ([Zanata](https://fedora.zanata.org/version-group/view/PriorityPackages/languages/nb), [CLDR](http://st.unicode.org/cldr-apps/v#/nb//), [Damned Lies](https://l10n.gnome.org/teams/nb/), [Wikipedia - Norwegian language](https://en.wikipedia.org/wiki/Norwegian_language), [Wikipedia - Bokmål](https://en.wikipedia.org/wiki/Bokm%C3%A5l)) how the two variants of Norwegian language are spelled and **Bokmål** is always spelled as **Bokmål**, with **a** with ring above, U+00E5, not plain **a**. If possible, please fix.

Otherwise no problem.

##### STEPS TO REPRODUCE

See the [transtats.xyz](http://transtats.xyz) main page, scroll down to Norwegian languages.

##### EXPECTED RESULTS

Correct spelling: **Norwegian Bokmål**

##### ACTUAL RESULTS

Incorrect spelling: **Norwegian Bokmal**

**Comment by sundeep-co-in** [comment]
thanks @rluzynski raising this!
