### ISSUE TITLE
404 not found if we pass // in the application url

### ISSUE THREAD

**Issue by spathare21** [transtats/transtats#152]
##### ISSUE TYPE

 - Bug Report

##### OS / ENVIRONMENT

```
Fedora 28 
```

##### SUMMARY

If we pass // in the url like http://localhost:8014//translation status//package it throws 404 not found error. 

##### STEPS TO REPRODUCE

```
Add // in the application url e.g http://<hostname>:8014//translation-status//package/ 
```

##### EXPECTED RESULTS

- // should be handled properly so that if we pass such option with URL it show some common/standard error message

##### ACTUAL RESULTS

- 404 not found

**Comment by bhavin192** [comment]
An URL with double slash `//` is also a valid URL (https://stackoverflow.com/a/20524044/6202405, https://tools.ietf.org/html/rfc3986), so I don't think we should handle this separately. `404 Not Found` is correct/standard error for such URLs. IMHO it's not a bug.
