### ISSUE TITLE
more flexible graph rules

### ISSUE THREAD

**Issue by sundeep-co-in** [transtats/transtats#153]
##### ISSUE TYPE

 - Feature Idea

##### SUMMARY

Graph rules should have an option to input one or more than one `build-tag / version` and a set of languages, which should generate stats representation in diff format (tag-wise) with statistics details - for a set of packages.

*For example*: lets say we need stats diff for tags f29 and f30 in 10 languages for 5 packages.

**Comment by sundeep-co-in** [comment]
thanks @smaitra-rh for suggesting this! You may want to add something to it.

**Comment by juhp** [comment]
In a why I would like to see some standard useful default rules provided.

I mean ideally (optimistically) if sufficient default rules exists, user would not have to create any but maybe this is naive thinking...

**Comment by sundeep-co-in** [comment]
Initially, graph rules were thought of the last `Advanced` tab we have in dashboard, where we create our own rule or search / filter criteria. Not sure, if we're calling this with a different name; what should be better way catering this feature?

**Comment by sundeep-co-in** [comment]
Packages having improper graph mapping should be excluded in the `new graph rule` form.

**Comment by spathare21** [comment]
Able to access Private graph rule using api. 
1. Have created a private rule rule5 which is only visible for logged in user. 
2. But if you hit the API Request http://localhost:8014/api/coverage/rule5 you will able to access it without Authorization.

**Comment by sundeep-co-in** [comment]
thanks @spathare21 
As of now, hiding private rules from API, ideally if user has `auth token` it could be accessed - shall work on that though!
