### ISSUE TITLE
504 Gateway timeout

### ISSUE THREAD

**Issue by spathare21** [transtats/transtats#154]
##### ISSUE TYPE

 - Bug Report

##### OS / ENVIRONMENT

```
Openshift Environment
```

##### SUMMARY
- We are getting 504 gateway timeout on sycn upstream jobs and sync translation platform intermittently 
##### STEPS TO REPRODUCE
- Open transtats
- Add any package ex. abrt.
- sync translation platform for ru string change job
- Observe response

```

```

##### EXPECTED RESULTS
- Job runs should be smooth/successfull without any error

##### ACTUAL RESULTS
- 504 gateway timeout

![screenshot from 2018-12-06 20-15-26](https://user-images.githubusercontent.com/23230884/49848988-a6b17100-fdfd-11e8-8ab5-ebb44a6119df.png)
![screenshot from 2018-12-06 20-11-44](https://user-images.githubusercontent.com/23230884/49848990-a74a0780-fdfd-11e8-815d-a196053a99e8.png)

**Comment by sundeep-co-in** [comment]
`one` work-around could be to try downloading the zip first before cloning the repository. download url should go something similar to: `https://<base-url>/<user>/<repo>/archive/<branch>.zip`

**Comment by sundeep-co-in** [comment]
@spathare21 can we close this?
