### ISSUE TITLE
Translation memory / database of translations

### ISSUE THREAD

**Issue by Jibec** [transtats/transtats#178]
Is there a way to save each translated string in a database? Either a TMX file or any tool to query data?

The usecase are as follow:

* help translators to search for an existing transltion,
* create quality checks

**Comment by sundeep-co-in** [comment]
I feel, the best time working on this is - when we will be working on implementing `verifytrans` job template. Hence this can be linked to https://github.com/transtats/transtats/issues/69

This feature could be basis to a host of new possibilities in Transtats. Thanks @Jibec :+1:

**Comment by sundeep-anand** [comment]
with the [upcoming](https://fedoraproject.org/wiki/Changes/LocalizationMeasurementAndTooling) feature, this change seems losing priority a bit in fedora!
