### ISSUE TITLE
graph of some packages looks irregular

### ISSUE THREAD

**Issue by spathare21** [transtats/transtats#18]
few of the branch/legend statistics are missing from graph for all the package.

*Instance*:
- http://transtats.devlab.redhat.com/

*Steps*:
- Hit the above transtats instance.
- Select packages libreport,python-meh,anaconda..etc.
- Observe the graph for all legends/branch.

*Actual*:
- some of the branch statistics are missing.

*Expected*:
- For all the branch/legends statistics should have to shown even if it is 0 %.
![stat1](https://cloud.githubusercontent.com/assets/23230884/20789272/aec220ae-b7d9-11e6-8b76-6dad9adb8701.png)
![stat2](https://cloud.githubusercontent.com/assets/23230884/20789274/aec538b6-b7d9-11e6-8f38-56a9409cf546.png)
![stat3](https://cloud.githubusercontent.com/assets/23230884/20789273/aec288e6-b7d9-11e6-95eb-032ad7b20e19.png)

**Comment by sundeep-co-in** [comment]
Exactly overlapped lines look missing. May be we find some fix here - when we return to polish `Package wise for enabled languages` view. I would take this as an enhancement rather a bug.

Thanks

**Comment by sundeep-co-in** [comment]
Some packages are getting irregular graph here - Is it possible to rectify them?

**Comment by spathare21** [comment]
Following is the list of packages which are getting irregular graph : 

- abrt
- candlepin
- gnome-abrt
- kexec-tools
- libreport
- selinux
- subscription-manager
- system-config-kickstart
- virt-manager

Also attached few screen captured 

![virt-manager](https://cloud.githubusercontent.com/assets/23230884/23739082/b4d41962-04c2-11e7-8b3f-6b62683fdc6e.png)

![abrt](https://cloud.githubusercontent.com/assets/23230884/23739087/ba7b7f0e-04c2-11e7-98e7-f503549bc71a.png)

![libreport](https://cloud.githubusercontent.com/assets/23230884/23739097/c6453690-04c2-11e7-893b-d67d17180365.png)

**Comment by juhp** [comment]
I wondering if barcharts would be better way to display package status per language/branch.

**Comment by spathare21** [comment]
Hi @sundeep-co-in ,

still the graphs of following packages have issue.

- authconfig. 
- candlepin  (0.4 branch French lang)
- Kecec-tools (stats for Spanish language shows two times)
- libpwquality
- libreport (rhel7 branch Marathi Lang)
- virt-manager (stats for Portuguese lang)
- subscription-manager (0.98.X branch stats)
- system-config-firewall 
- webhh

**Comment by sundeep-co-in** [comment]
Thanks @spathare21 fixing...
