### ISSUE TITLE
Legend names are very compact to the icons.

### ISSUE THREAD

**Issue by spathare21** [transtats/transtats#19]
*Instance*:
- http://transtats.devlab.redhat.com/

*Steps*:
- Hit the above transtats instance.
- Select packages libreport,python-meh,anaconda..etc.
- Observe the legends and its name.

*Actual*:
- Legend names are very compact/near to the icons. 

*Expected*:
- There should be an little bit space between legend name's and icon.

![legends_name](https://cloud.githubusercontent.com/assets/23230884/20789410/4f6a19bc-b7da-11e6-83bf-f7544a82123a.png)

**Comment by sundeep-co-in** [comment]
filtration of branches and making it to show only active / meaningful branches may help here.
