### ISSUE TITLE
gear up envs for fedora 30 onward

### ISSUE THREAD

**Issue by sundeep-anand** [transtats/transtats#191]
##### ISSUE TYPE

 - Bug Report

##### OS / ENVIRONMENT

```
Fedora 30
```

##### SUMMARY

Vagrant and Docker envs may need some refactor to work on `fedora 30`

**Comment by vikasmulaje** [comment]
@sundeep-co-in Working on this.
Found out that this issue is related to Changed Selinux policy for containers.
check https://github.com/moby/moby/pull/5910
https://github.com/docker/libcontainer/pull/47
Will send a fix for this

**Comment by sundeep-co-in** [comment]
thanks @vikasmulaje
