### ISSUE TITLE
[python-meh][rhel7-branch] Line graph for rhel7-branch incorrect.

### ISSUE THREAD

**Issue by spathare21** [transtats/transtats#20]
Instance:
http://transtats.devlab.redhat.com/

*Steps*:
- Hit the above transtats instance.
 - Select packages python-meh.
 - Observe the line graph of rhel-7 branch.
![stat_graph](https://cloud.githubusercontent.com/assets/23230884/20789935/49243f5e-b7dc-11e6-93bf-966d09df004c.png)

**Comment by sundeep-co-in** [comment]
This seems to be fixed with https://github.com/transtats/transtats/issues/18
