### ISSUE TITLE
Patch application broken

### ISSUE THREAD

**Issue by ernestask** [transtats/transtats#203]
##### ISSUE TYPE

 - Bug Report

##### OS / ENVIRONMENT
Fedora 31

##### SUMMARY
The approach taken in https://github.com/transtats/transtats/blob/91fa3a2af45c3b464cb7e7e12892a59913fb4f61/dashboard/engine/action_mapper.py#L608 seems to result in incorrect stats being displayed in my case.

Paths like the following can be observed in http://transtats.devlab.redhat.com/jobs/log/a7f69115-3038-4a19-93c3-34740f730ead/detail:

```
'dashboard/sandbox/libreport/libreport-2.1.11/b/po/uz.po, '
'dashboard/sandbox/libreport/libreport-2.1.11/b/po/ach.po, '
```

##### STEPS TO REPRODUCE
Unfortunately, this is only applicable to an internal Red Hat instance.

http://transtats.devlab.redhat.com/jobs/yml-based?template=syncdownstream&package=libreport

Start a job for rhel-7.8-candidate.

##### EXPECTED RESULTS
ja is at 100% and no b/ paths exist, i.e. patches are applied correctly.

##### ACTUAL RESULTS
Patches are applied incorrectly.

```
msgattrib --untranslated po/ja.po
po/ja.po:771: duplicate message definition...
po/ja.po:757: ...this is the location of the first definition
po/ja.po:1354: duplicate message definition...
po/ja.po:1087: ...this is the location of the first definition
po/ja.po:1358: duplicate message definition...
po/ja.po:1092: ...this is the location of the first definition
msgattrib: found 3 fatal errors
```

**Comment by sundeep-co-in** [comment]
thank you @ernestask for reporting this!

**Comment by sundeep-co-in** [comment]
Hi @ernestask ,

While debugging this, I need your little help.

Please confirm latest `POT` is merged with all existing `PO` files, and on top of that `dashboard/sandbox/libreport/0036-Translation-updates.patch` is being applied?
 
I guess there could be some string mismatch, please refer: http://transtats.devlab.redhat.com/jobs/log/6fc61f91-3bcc-4f21-9157-0c17e47659fe/detail

Wondering for me, `msgattrib` gives following (and this string is a part of diff):

```
#: ../src/gui-wizard-gtk/wizard.c:3575
msgid ""
"In order to enable the built-in screencasting functionality the package fros-"
"gnome has to be installed. Please run the following command if you want to "
"install it.\n"
"\n"
"<b>su -c \"yum install fros-gnome\"</b>"
msgstr ""
```

Anyways, I'll update more on this!

Thanks again!

**Comment by ernestask** [comment]
master is the wrong branch here.

https://fedora.zanata.org/iteration/view/libreport/rhel7
https://gitlab.cee.redhat.com/abrt/libreport/tree/rhel7

**Comment by sundeep-co-in** [comment]
ah, a couple of things:

- sorry was looking at `https://github.com/abrt/libreport` `rhel7_include_reported_to_in_sc` branch
- as https://fedora.zanata.org/iteration/view/libreport/rhel7 is locked; cannot be accessed over API

**Comment by ernestask** [comment]
Argh, we’re in the middle of migrating to Weblate, which is complicating everything. Made writable again.
