### ISSUE TITLE
fedora migration to weblate

### ISSUE THREAD

**Issue by Jibec** [transtats/transtats#205]
hello,

users are confused because transtats shows obsolete url in transtats.
Could you please update all of them?

Thanks for your help

**Comment by sundeep-co-in** [comment]
sure, tried to update a couple of packages at https://transtats.stg.fedoraproject.org/packages/
however, somehow packages with alerts and/or a lock at https://translate.fedoraproject.org/projects/ are not getting sync'd. I'm looking into that and shall update with more details.

**Comment by sundeep-anand** [comment]
Sync with [weblate](https://translate.fedoraproject.org/) is not very smooth. Though I have given `auth token` for API calls, it seems to restrict response after 6-7 calls in a sequence.

Transtats makes calls for all related packages at-least once a day and many packages do not get sync'ed. Perhaps I'm missing on some policy etc.

**Comment by sundeep-anand** [comment]
migration of initial set of packages is done, thanks!

**Comment by sundeep-anand** [comment]
### Seems following packages are still migrating ...

1. libuser - https://pagure.io/libuser/issue/43
2. MediaWriter - https://github.com/FedoraQt/MediaWriter/issues/224
3. system-config-kdump - https://bugzilla.redhat.com/show_bug.cgi?id=1789353
4. system-config-language - https://pagure.io/system-config-language
5. udisks - https://github.com/storaged-project/udisks/issues/719

**Comment by Jibec** [comment]
really? I think they did not migrate, and don't wish to or can't for 
whatever reason.
nothing we can do

**Comment by sundeep-anand** [comment]
thanks for reporting. this has been done!
