### ISSUE TITLE
display stats in words along with messages

### ISSUE THREAD

**Issue by spathare21** [transtats/transtats#21]
*Instance*:
- http://transtats.devlab.redhat.com/

*Steps*:
- Hit above transtats instance.
- Select packages libreport/anacond or any.
- Observe the line graph of master branch.
- Compare that languages percent translated with translation percent shown on https://fedora.zanata.org/iteration/view/libreport/master?dswid=-3307 

![chines_trans](https://cloud.githubusercontent.com/assets/23230884/20790441/57b2055e-b7de-11e6-9ed0-22488b986862.png)
![italian_trans](https://cloud.githubusercontent.com/assets/23230884/20790442/57b5034e-b7de-11e6-8828-9db738cdf1c7.png)
![japanes](https://cloud.githubusercontent.com/assets/23230884/20790443/57ba1c9e-b7de-11e6-9569-6bffd994d3c0.png)

![screenshot from 2016-12-01 15-54-02](https://cloud.githubusercontent.com/assets/23230884/20790591/08f94854-b7df-11e6-9583-ffe23461756b.png)

**Comment by sundeep-co-in** [comment]
Thanks for pointing this! In `TS` translation %age are calculated on the basis on messages. I think we can see some fix soon.

**Comment by sundeep-co-in** [comment]
Can we display in words and messages both? and user can toggle!
