### ISSUE TITLE
Job detail page enhancements

### ISSUE THREAD

**Issue by sdp5** [transtats/transtats#211]
##### ISSUE TYPE

 - Feature Idea

##### SUMMARY

Job detail page could be integrated in a way to broadcast the results a bit more.
Initial ideas are `email` and `bugzilla integration`.

**Comment by sundeep-anand** [comment]
may be alerts if stats of any required language seem missing

**Comment by sundeep-anand** [comment]
> may be alerts if stats of any required language seem missing

this could be subset of https://github.com/transtats/transtats/issues/215

**Comment by krisnababu** [comment]
While pushing translations to memsource, if the source repository doesn’t have .po for selected locale, Job will run successfully, but there is no indication/notification to inform the job owner that there is no .po available for selected locale.                                           Even if a .po file available for selected language at source repository it is only being used when the locale code is exactly matching, for e.g. if you select ja_JP and source repo has ja.po, then that file is not being used for intended operation!

**Comment by sundeep-anand** [comment]
> While pushing translations to memsource, if the source repository doesn’t have .po for selected locale, Job will run successfully, but there is no indication/notification to inform the job owner that there is no .po available for selected locale. Even if a .po file available for selected language at source repository it is only being used when the locale code is exactly matching, for e.g. if you select ja_JP and source repo has ja.po, then that file is not being used for intended operation!

thanks bringing this up.. order could be first, check with the language alias if not found set some warnings in the job's log.

**Comment by sdp5** [comment]
Notifications in Transtats are getting difference direction which may diverge with this!
