### ISSUE TITLE
We are able to select both release steam at a time while adding package.

### ISSUE THREAD

**Issue by spathare21** [transtats/transtats#24]
##### ISSUE TYPE

 - Bug Report
 
##### OS / ENVIRONMENT

```
Fedora 25 + Firefox 50
```
##### SUMMARY

- While adding a package we are able to select both checkbooks of release stream i.e we are able to select RHEL as well as Fedora stream at one time.
##### STEPS TO REPRODUCE
- Open transtats home.
- Click on Settings
- Click on Package.
- Click on Add package on top right corner.
- You will see the add packages field.
- Go to the Release stream section and click on release streams.
- Click on both the check box.
- Observe the behavior.

##### EXPECTED RESULTS
- We should able to select only one release stream at a time.
- After selecting another first should have to unchecked automatically. like language set option
##### ACTUAL RESULTS
- Able to select both release stream.

**Comment by sundeep-co-in** [comment]
I believe a package has following relationships:

Package - Upstream : One-to-One
Package - Translation Platform : One-to-One
Package - Release Streams : One-to-Many

@sshedmake how do you think? @spathare21 which point/concept made you feel package should have one-to-one relationship with release stream? 

As we have this being constructing in `TS` making this open for discussions.

**Comment by sshedmake** [comment]
@sundeep-co-in: Yep, above relationships for a 'package' looks good.
