### ISSUE TITLE
The list of branch names are not sorted on pipeline's configuration page.

### ISSUE THREAD

**Issue by krisnababu** [transtats/transtats#270]
##### ISSUE TYPE

 - Bug Report

##### OS / ENVIRONMENT / VERSION

Fedora 35 / Transtats 0.8.6

```

```

##### SUMMARY

Branch list of a package is not sorted on pipelines configuration page

##### STEPS TO REPRODUCE

1. Load transtats environment.
2. Go to a pipeline's configuration page.
3. Click on branch: _drop-down-list_
4. The list is not sorted.

```

```

##### EXPECTED RESULTS

The list of branch names should be sorted.
##### ACTUAL RESULTS

The list of branch names are not sorted.
![transtats-branch-list-sorting](https://user-images.githubusercontent.com/25174566/164236638-68d2b8f3-e854-4c58-9b59-d9173a1df81f.png)

**Comment by sdp5** [comment]
this has been achieved in https://github.com/transtats/transtats/commit/cd39b13c0249128ed1d107ad42e3532d8a090e4b
