### ISSUE TITLE
Work around memsource plural strings limitation

### ISSUE THREAD

**Issue by ekohl** [transtats/transtats#290]
##### ISSUE TYPE
 - Feature Idea

##### OS / ENVIRONMENT / VERSION
Pull from Transifex and push into Memsource (so all backend API work).

##### SUMMARY

Transifex has [implemented language plural rules](https://community.transifex.com/t/important-update-languages-plural-rules/2832) but Memsource doesn't so this (tracked by them in TP request 79944). The result is that it rejects es, fr and pt_br.

As a workaround transtats could transform the complex version into a simple version so at least it can be imported into memsource automatically. Once Memsource has implemented the feature, the workaround can be removed.

##### STEPS TO REPRODUCE
Use a complex `Plural-Forms`. For example, from https://github.com/theforeman/foreman/blob/b06f500d51f6655f0fe1fe6e6ac24a2d5e81b694/locale/es/foreman.po#L39-L40
```
Plural-Forms: nplurals=3; plural=n == 1 ? 0 : n != 0 && n % 1000000 == 0 ? 1 : 2;
```
https://github.com/theforeman/foreman/blob/b06f500d51f6655f0fe1fe6e6ac24a2d5e81b694/locale/fr/foreman.po#L48-L49
```
Plural-Forms: nplurals=3; plural=(n == 0 || n == 1) ? 0 : n != 0 && n % 1000000 == 0 ? 1 : 2;
```

https://github.com/theforeman/foreman/blob/b06f500d51f6655f0fe1fe6e6ac24a2d5e81b694/locale/pt_BR/foreman.po#L41-L42
```
Plural-Forms: nplurals=3; plural=(n == 0 || n == 1) ? 0 : n != 0 && n % 1000000 == 0 ? 1 : 2;
```

##### EXPECTED RESULTS
A language with complex Plural-Forms can be pulled from Transifix and pushed into Memsource

##### ACTUAL RESULTS
The pushed language in Memsource shows an error `INTERNAL_ERROR: Could not find all plural categories`.

**Comment by sdp5** [comment]
Upload prehook `simplify_plural_forms_in_po_header` has been implementation as a quick fix in https://github.com/transtats/transtats/commit/c7259027406eb2e54444cc07addf26ab120dfd6a .

**Comment by ekohl** [comment]
Thanks! That looks rather straight forward. Left a trivial comment inline.
