### ISSUE TITLE
Uncertain error message while running `Sync Package Build System` Job

### ISSUE THREAD

**Issue by krisnababu** [transtats/transtats#298]
##### ISSUE TYPE

 - Bug Report

##### OS / ENVIRONMENT / VERSION

  Fedora 36

```

```

##### SUMMARY

While running `Sync Package Build System` job for a package which is not added to transtats, getting error "Alas! Something unexpected happened."
 Job is successful though.
Attaching screenshots 1. [Uncertain error message](https://drive.google.com/file/d/1KcIs_7C8Mq6nHqFqCUfPLaxF6eqwFZKx/view?usp=sharing) 2. [Corresponding successfull job log](https://drive.google.com/file/d/1yUF63CJhde3hv7l51RYUDRDV_p_h3nB8/view?usp=sharing).

##### STEPS TO REPRODUCE

1. Run `Sync Package Build System` Job for the package which is not added to transtats. Provide required field values.
2. Uncheck "Dry Run" and "Run Job"

```

```

##### EXPECTED RESULTS

Error message should be more specific rather uncertain (e.g. "Alas! Something unexpected happened.")

##### ACTUAL RESULTS

Uncertain error message "Alas! Something unexpected happened."

**Comment by sdp5** [comment]
committed a [fix](https://github.com/transtats/transtats/pull/295/commits/585cf45d694d0aef9dd99d38f0c720a1090f8e84)

**Comment by krisnababu** [comment]
Thank you very much for the quick fix! Not error message is [descriptive](https://drive.google.com/file/d/1ZUOvQEgo43FWYq4UpOKQYmpq4zRmux59/view?usp=sharing).
