### ISSUE TITLE
LogIn page not loading while the ts_auth_system is fedora

### ISSUE THREAD

**Issue by krisnababu** [transtats/transtats#305]
##### ISSUE TYPE

 - Bug Report
 

##### OS / ENVIRONMENT / VERSION

fedora

```

```

##### SUMMARY

When the "TS_AUTH_SYSTEM": "fedora" in keys.json, the login page is not loading, getting ["This site can't be reached"](https://drive.google.com/file/d/17-gEppf3HiN6pSyko-CapZDloL00k8o8/view?usp=sharing)

##### STEPS TO REPRODUCE

Set "TS_AUTH_SYSTEM": "fedora" in keys.json
Goto localost:8080 and click on login

```

```

##### EXPECTED RESULTS

FAS login should available
##### ACTUAL RESULTS

Page not loading

**Comment by sdp5** [comment]
maybe the fedora-auth-service moved to another URL, need to get an update from fedora-infra on this.

**Comment by ryanlerch** [comment]
I have tried a suggestion made in https://pagure.io/fedora-infrastructure/issue/11207 but it doesnt seem to work -- it appears the issue is transtats itself (i.e. the django oidc plugin being used) is providing a http callback url when ipsilon needs a https one. see the ticket for more info

**Comment by sdp5** [comment]
@pnemade anyone interested to work on this?

**Comment by sdp5** [comment]
https://github.com/jazzband/django-oauth-toolkit could be an option.

**Comment by sdp5** [comment]
thank you @krisnababu and @ryanlerch 

this has been fixed!

**Comment by juhp** [comment]
Thank you
