### ISSUE TITLE
RFE: improve presentation of stats

### ISSUE THREAD

**Issue by juhp** [transtats/transtats#45]
I think it is better to use barcharts/histograms (or just dots) to display charts for statistics.
The lines in the current charts don't really have so much meaning.

You could either group bars by language or branch etc.

**Comment by sundeep-co-in** [comment]
@juhp dots with thin line graphs looks proper. now test branches are filtered and we have one graph at a time. You may please have a look at changes at test env.

**Comment by juhp** [comment]
Thanks looks better now.

I think the branches need to be order (lexically say).

It occurred to me that a simple table of lang % vs branch would be very informative.
If that works out well it could well be the right default presentation.
