### ISSUE TITLE
Translation percentage/points for protuguese nad spanish language shown two times becase of alias

### ISSUE THREAD

**Issue by spathare21** [transtats/transtats#48]
Translation percentage on Graph for few packages of Portuguese and Spanish languages shown two times. because of the lang alias.

![screenshot from 2017-04-05 11-52-24](https://cloud.githubusercontent.com/assets/23230884/24692576/3c216eb8-19c9-11e7-9fad-7d8c090cef2c.png)

![screenshot from 2017-04-05 11-53-40](https://cloud.githubusercontent.com/assets/23230884/24692579/4230135e-19c9-11e7-8e82-b70cb0d410a6.png)

![screenshot from 2017-04-05 11-54-08](https://cloud.githubusercontent.com/assets/23230884/24692594/56d96a76-19c9-11e7-82b5-40eb74117c7c.png)

**Comment by juhp** [comment]
Good catch, yes the aliases need to be combined.

**Comment by sundeep-co-in** [comment]
taking larger value :)
