### ISSUE TITLE
Upstream sync issues

### ISSUE THREAD

**Issue by sundeep-co-in** [transtats/transtats#64]
##### ISSUE TYPE

 - Bug Report

##### SUMMARY

- [x] Handle double click event on upstream repository sync button.
- [x] Show logs for failed jobs.

**Comment by sundeep-co-in** [comment]
Can we notify upstream that there are some new translations available to get pulled?

**Comment by Jibec** [comment]
We should not, it will spam them and it should be a translation platform feature (most have it)

**Comment by sundeep-co-in** [comment]
this has been achieved with https://github.com/transtats/transtats/releases/tag/0.1.6-rc.1
