### ISSUE TITLE
string change detection

### ISSUE THREAD

**Issue by sundeep-anand** [transtats/transtats#69]
##### ISSUE TYPE

 - Feature Idea

##### SUMMARY

One of the points discussed at **flock17** is "String change detection" mostly after string freeze, reflecting them at translation platform and building package with new translated-strings aimed for the said release.

Lets keep this in discussion for a while, before we reach at some solution/conclusion about solving this.

@juhp @pnemade @pravins I invite you for putting your views here. :smiley:

**Comment by sundeep-co-in** [comment]
from `l10n` meetings: transtats should enable out-of-schedule string change tracking for Fedora 28

**Comment by sundeep-co-in** [comment]
One of the options I guess is to clone package from `git repo` every day after `string freeze` and check for difference in `POT` file if any till next `milestone` in release schedule.

@Jibec Would like to invite you for putting your thoughts on this here.

**Comment by sundeep-co-in** [comment]
by **Jibec**: If we have new warnings or a decrease in translation' progress, it probably means a string breakage.

**Comment by juhp** [comment]
I wonder if downstream tracking would be sufficient?

**Comment by Jibec** [comment]
Le 30 octobre 2017 04:13:57 GMT+01:00, Jens Petersen <notifications@github.com> a écrit :
>I wonder if downstream tracking would be sufficient?

Well, I suggest to first start measures of differences and trigger some warnings, then the answer will be obvious.
-- 
Jean-Baptiste Holcroft

**Comment by sundeep-co-in** [comment]
Solution to this could be ...

1. fetch `SRPM` of latest build from koji build system (here we get `NVR`)
2. generate `POT` from `SRPM` and compare with Translation Platform `POT`
    - new strings not pushed to translation platform for translation!
3. merge translations from translation platform to POT generated from SRPM and compare with PO present in SRPM
    - this will be - `translations done with old POT vs actual translations required`
    - and I think this can detect string breakage

Now, points are:

1. How to track out-of-schedule string change?
2. What should we do to fix this? `Notifications` or `Automation`?

Actually, this is how we can measure differences. Anyways lets keep this open to discussions as this looks dependent on https://github.com/transtats/transtats/pull/78

@sshedmake Inviting you to put your views too.

**Comment by sshedmake** [comment]
Yes, 2. verifies that POT at Translation platform is outdated.
Respective owner should be notified first about POT being outdated at Translation platform.

Agreed with 3.

Notifications looks good. https://wiki.gnome.org/ReleasePlanning/Freezes/#String_Freeze could be useful.

**Comment by sundeep-co-in** [comment]
thanks @sshedmake 
Generating `POT` from `SRPM` is more of package specific task, some packages may have similar steps whereas some may have different.
Short term solution here could be: identify most common step and implement that to see some results.
Long term solution is leverage on `Transtats Jobs`

**Comment by sundeep-co-in** [comment]
@juhp @pnemade I guess, as, we are now slowly moving towards solution to this, I seek your inputs.

Hi @bexelbie, just wanted to check with you, if you have some inputs on this!

**Comment by sshedmake** [comment]
An example indicating string freeze break could be: https://mail.gnome.org/archives/gnome-i18n/2017-November/msg00001.html

**Comment by Jibec** [comment]
You may have a look at appstream, Richard Hughes does extract translation status from packages with a C script: https://github.com/ximion/appstream and https://github.com/hughsie/appstream-glib

Reusing existing libraries would probably help a lot to save time ;)

Here is an example of data extracted: https://jibecfed.fedorapeople.org/l10n/appdata-fr/xml/alexandria.desktop.xml

**Comment by bexelbie** [comment]
Would it be possible to optimize by just listening to fedmsg for new source uploads for the most important packages?  That gets us a starting point.  (If this is a basic repeat, I am sorry).

**Comment by sundeep-co-in** [comment]
@aeng need your views here.

**Comment by aeng** [comment]
I can only comment on how Zanata can help with this as I am not sure what is the process used to get the updated source to Zanata. But assuming the updated source is being pushed to Zanata, 1 option is to use the project webhook send out webhook event on that project. We got a webhook event for when a document being added/removed from a project which I think can be useful in this use case.
http://docs.zanata.org/en/release/user-guide/projects/project-settings/#document
fedora.zanata.org is running on old version of Zanata at the moment which only has `100% translated doc event`, we are still working on the upgrades.

But if you wish to eliminate dependency on Zanata, another way would be setting up a centralized service (Jenkins perhaps) which listens to an update on the source repository (e.g. Github). This will not be an easy task since you will need to identify all the packages, and their source repo, not to mention a lot of maintenance work to be done over time. But by using this, you can configure the job to send an event to any services that require to act on the change, and also be able to configure it to push the updated source to Zanata automatically.

**Comment by sundeep-co-in** [comment]
thanks for your inputs! as downstream tracking is now achieved, we came closer to this - as, in - this is just the next step. Along with statistics comparison we need to compare POT and PO both (resources) from all three places.

**Comment by sundeep-co-in** [comment]
moving this to development

**Comment by sundeep-co-in** [comment]
Implementation of `stringchange` job template is completed. The feature will be shipped in `release 0.1.6`
Next, is `verifytrans` job template!

**Comment by juhp** [comment]
Threre should really be some UI for this eventually - to be the jobs should just be hidden and the results exposed in some UI/tab.

**Comment by sundeep-co-in** [comment]
Steps in `verifytrans` basically are:

1. Download and latest `SRPM` from build system.
2. Create fresh translation template `(POT)` from source tarball.
3. Pull translations from translation platform.
4. Merge pull translations to newly created `POT` - **set 1**
5. Apply patch and filter PO files - **set 2**
6. Compare **set 1** and **set 2** - find diff for each locale.

This is complex but results could be extremely helpful.

**Comment by sundeep-co-in** [comment]
Meanwhile, before `verifytrans` we should work on scheduling `stringchange` job as per `string freeze date` in release schedule!
