### ISSUE TITLE
Cannot run app on 'Fedora 25' box, 'sudo vagrant up' fails with upstream 'transtats' (stage branch)

### ISSUE THREAD

**Issue by sshedmake** [transtats/transtats#81]
##### ISSUE TYPE

 - Bug Report

##### OS / ENVIRONMENT

```
[transtats@localhost transtats]$ rpm -q docker ansible vagrant
docker-1.12.6-7.gitae7d637.fc25.x86_64
ansible-2.4.0.0-1.fc25.noarch
vagrant-1.8.5-3.fc25.noarch
[transtats@localhost transtats]$ cat /etc/fedora-release 
Fedora release 25 (Twenty Five)
[transtats@localhost transtats]$ sudo vagrant plugin install vagrant-hostmanager
Installing the 'vagrant-hostmanager' plugin. This can take a few minutes...
Installed the plugin 'vagrant-hostmanager (1.8.7)'!
[transtats@localhost transtats]$ echo $?
0

```

##### SUMMARY

Cannot run app on 'Fedora 25' box, 'sudo vagrant up' fails with upstream 'transtats' (stage)

##### STEPS TO REPRODUCE

1. Checkout upstream transtats (stage) source code

```
2. sudo vagrant up
```

##### EXPECTED RESULTS

No error

##### ACTUAL RESULTS

TASK [setup : Setup transtats keys] ********************************************
fatal: [default]: FAILED! => {"changed": true, "cmd": "cp /workspace/transtats/settings/keys.json.example /workspace/transtats/settings/keys.json", "delta": "0:00:00.105975", "end": "2017-10-18 06:54:38.411890", "failed": true, "msg": "non-zero return code", "rc": 1, "start": "2017-10-18 06:54:38.305915", "stderr": "cp: cannot stat '/workspace/transtats/settings/keys.json.example': Permission denied", "stderr_lines": ["cp: cannot stat '/workspace/transtats/settings/keys.json.example': Permission denied"], "stdout": "", "stdout_lines": []}
	to retry, use: --limit @/home/transtats/github/sundeep_anand/transtats_stage/transtats/devel/ansible/playbook.retry

See also: https://paste.fedoraproject.org/paste/4MDLkGQ8fl6YVeqOZ--tnA

**Comment by sundeep-co-in** [comment]
I feel there have been some discussions around... https://github.com/moby/moby/issues/1295 https://github.com/geerlingguy/awx-container/issues/7

**Comment by sundeep-co-in** [comment]
Closing this as fedora 25 has reached EOL: https://fedoramagazine.org/fedora-25-end-life/
