### ISSUE TITLE
Translation Snapshots

### ISSUE THREAD

**Issue by sundeep-anand** [transtats/transtats#85]
##### ISSUE TYPE

 - Feature Idea

##### OS / ENVIRONMENT

All

##### SUMMARY

`Are we improving or decreasing since last stream?`

Translation snapshots can be taken at regular intervals for release branches and/or packages which can be represented as in history or trends.

` What are the pain points?`

This can be little tricky, may be a mechanism by which translators inputs can be collected at one place!

**Comment by Jibec** [comment]
by pain points, I meant: which packages or languages have difficulties and why. This should only be numbers and error checking run with actual transtats data.
