### ISSUE TITLE
formatting issues

### ISSUE THREAD

**Issue by sundeep-co-in** [transtats/transtats#88]
##### ISSUE TYPE

 - Bug Report

##### SUMMARY

- [ ] When there is columns with numbers, they all should have the same number of decimal point, and be align on right.
- [ ] Javascript filters to sort columns

**Comment by spathare21** [comment]
- [ ] Package selection dropdown opens on upside which hides the search option

![package_dd](https://user-images.githubusercontent.com/23230884/37087338-0812a50a-2220-11e8-996f-380bb0c5e578.png)

**Comment by spathare21** [comment]
- [ ] Package name and Select build tag should be filtered automatically while typing character. in YMl based jobs

![screenshot from 2018-03-07 16-33-07](https://user-images.githubusercontent.com/23230884/37089034-4c74de20-2225-11e8-9407-94675f6fb16d.png)

![screenshot from 2018-03-07 16-32-31](https://user-images.githubusercontent.com/23230884/37089039-506f1392-2225-11e8-8875-0b8eb3c013a1.png)

**Comment by sundeep-co-in** [comment]
these reports go void after https://github.com/transtats/transtats/pull/167
