### ISSUE TITLE
"DataError: unsupported Unicode escape sequence" while adding new package

### ISSUE THREAD

**Issue by spathare21** [transtats/transtats#93]
##### ISSUE TYPE

 - Bug Report

##### OS / ENVIRONMENT

```
Fedora 26 

```

##### SUMMARY
When I am trying to add new package with  https://translate.zanata.org as translation platform instance it throws "DataError in settings/packages/new"

##### STEPS TO REPRODUCE
- Login to transtats as admin.
- Click on dashboard.
- Packages - > Add package.
- try to add  package 
-- name: candlepin
-- upstream_url: https://github.com/candlepin/candlepin
- And select translation platform as transtate.zanata.org 
- Check fedora
- Click Add package
- Observe the error.

```

```

##### EXPECTED RESULTS
- Package should be added successfully if valid.
- If any wrong input throw specific error. 

##### ACTUAL RESULTS
- Throwing DataError exception

#####Note
- Facing this issue only if i select translate.zanata.org  as translation platform 
- Attached screen captured and logs.

![screenshot from 2017-11-08 10-46-34](https://user-images.githubusercontent.com/23230884/32534975-f1cd06f6-c44f-11e7-91f8-21955c52c82d.png)

[data_error.txt](https://github.com/transtats/transtats/files/1452820/data_error.txt)

**Comment by sundeep-co-in** [comment]
We are getting some UTF-8 data from some of the APIs so, now on-wards need to create database with UTF-8 support.

`CREATE DATABASE $DATABASE_NAME ENCODING = 'UTF-8' LC_CTYPE = 'en_US.utf8' LC_COLLATE = 'en_US.utf8' template = template0;`

**Comment by sundeep-co-in** [comment]
@spathare21 Is something left here?

**Comment by spathare21** [comment]
@sundeep-co-in nope everything is done, you can close it.

**Comment by sundeep-co-in** [comment]
thanks, closing!
